### ISSUE TITLE
Start Menu broke on latest fast ring release

### ISSUE THREAD

**Issue by vultureman** [passionate-coder/Classic-Start#18] opened 2018-06-22 23:13 UTC
I've been on fast ring release for a few months - no issues with classic start.

Just broke today - fails to come up, or only the bottom inch of the menu comes up. Restart does not resolve it.

Newest version as of today is Build 17692.rs_prerelease.180609-1317

Note - I'm not expecting a fix from this, as anyone running fast ring should expect stuff to break. I'm just giving you a heads up that it's going to probably break again with the next major consumer release, as the original author expected, and that you might be able to get ahead of it by looking at the most recent fast ring release.

**Comment by Matjaz65** [comment] 2018-06-29 17:12
Same issue in 17704.

**Comment by XenHat** [comment] 2018-06-30 19:12
Closing this as a duplicate of #11

**Closed by XenHat** 2018-06-30 19:12 UTC
Labels: help wanted, need fix
