### ISSUE TITLE
Crashes explorer (Windows 8)

### ISSUE THREAD

**Issue by ComradeCommie** [passionate-coder/Classic-Start#47] opened 2018-07-20 04:56 UTC
When I open the menu (settings panel is fine) the thing crashes. If i need to supply a log, may you tell me how?

**Comment by ibuprophen1** [comment] 2018-07-20 13:22
@ComradeCommie, just by stating that it crashes doesn't help figure out what/how it crashed... 

This could be something different crashing that prevented the Classic Start from working or even causing Classic Start from working that may or may not be tied to Classic Start. 


~Ibuprophen

**Comment by ge0rdi** [comment] 2018-07-20 16:03
> When I open the menu (settings panel is fine) the thing crashes.

What exactly does crash? Is it `explorer.exe`?
Could you provide at least screenshot from the _crash_?

**Comment by ComradeCommie** [comment] 2018-07-20 19:07
I'll do that, but I can't describe the crash past much just the menu opening, freezing explorer (the whole shell) and itself then eventually not responding and crashing.

**Comment by ibuprophen1** [comment] 2018-07-20 20:13
@ComradeCommie, try your best to duplicate the crash in question by mimicking what you had done for the original crash in question. 

Here's just a little helper regarding a screenshot for certain items like this (to help prevent the need for a mouse)... 

Do the following fluid like (one then the next then release them both):

On the keyboard, press and hold the "Windows" Key and then, right after that key is pressed, press the "Print" Key once then release them both. 

The screenshot will be in the Pictures folder within your Profile User Files. You'll see a folder named Screenshots with the image in there. 

Sorry for the lengthy explanation but, I just wanted to be sure that there would be no confusion. 

Good Luck! 😀


~Ibuprophen

**Comment by ge0rdi** [comment] 2018-07-20 20:53
@ComradeCommie 
Please, get [ProcDump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump) tool and run this from command line:

    procdump.exe -e explorer.exe

Then replicate the crash. It should create crash dump file (`explorer.exe_*.dmp`).
Attach the dump here.

**Comment by ComradeCommie** [comment] 2018-07-20 22:04
@ibuprophen1 No screenshots needed, like what I said, explorer crashes and restarts along with classic start.

@ge0rdi GitHub doesn't support log files, so I'm going to link to dropbox and put the dumps in there. I hope that is okay. https://www.dropbox.com/s/dx79vc1lvcnwd4r/explorer.exe_180720_145948.dmp?dl=1

**Comment by ge0rdi** [comment] 2018-07-20 22:31
Thanks.
Though, I've realized that we don't store symbols. So I can't see much in the dump :(

Please, replace `ClassicStartMenuDLL.dll` with this one [ClassicStartMenuDLL.dll.zip](https://github.com/passionate-coder/Classic-Start/files/2215637/ClassicStartMenuDLL.dll.zip) and repeat the process. This is custom built DLL, so I have symbols for it.

**Comment by ComradeCommie** [comment] 2018-07-20 22:59
When I replaced the DLL the start menu works but now looks like the attachment.
![screenshot 2](https://user-images.githubusercontent.com/36094486/43028648-e4eca7bc-8c35-11e8-9d14-2e6b7f576994.png)

**Comment by ge0rdi** [comment] 2018-07-20 23:27
Hmm, that may be caused by DLL version mismatch.
Though interesting that crashes don't occur when there is no skin used.

You can try to install latest nightly build from here:
https://ci.appveyor.com/project/passionate-coder/classic-start/build/artifacts

If it will crash again, please, create dump and upload it somewhere.
We have now symbols stored for this latest buils, so it will be easier to analyze crash dumps.

Also you may try to disable skin in settings - `Skin` tab -> select `<No Skin>` in combo box.
Eventually this may stop crashing (until a fix will be available).

**Comment by ComradeCommie** [comment] 2018-07-21 01:02
Ran it again, no skin's fine, enabled Aero skin, crash, 8 skin, crash, seems like no skin is the only working on. Dump here: https://www.dropbox.com/s/2f2vpzhyxfvtay5/explorer.exe_180720_180155.dmp?dl=1

**Comment by ComradeCommie** [comment] 2018-07-21 10:14
Well, that sucks. I'll try to adapt to the regular metro menu, thanks for the help. I still wonder, why does it only crash with the skin and not all the time if that is the case?

**Comment by ge0rdi** [comment] 2018-07-21 10:18
> I still wonder, why does it only crash with the skin and not all the time if that is the case?

Because the mentioned COM interface (`IImmersiveLauncherThumbnailProvider`) is used only when skin is being drawn.

**Closed by ge0rdi** 2018-07-21 10:18 UTC
